// OKO — bundle the country flag set used by contact cards (tracked readout,
// vessel cards, hover card).
//
// Source: flag-icons (github.com/lipis/flag-icons), MIT. Pulled from the npm
// registry as a versioned tarball so the bake is reproducible; only the ISO
// 3166-1 flags in 4:3 are kept (no sub-national / organisation flags — cards
// flag STATES: aircraft registration, airports, ship MMSI MID).
//
// Output (src/data/local_data/flags/):
//   4x3/{iso2}.svg      one file per country, lazy-loaded by countryFlags.js
//   countries.js        `COUNTRIES` [{code, name}] + FLAG_ICONS_VERSION, so the
//                       runtime can map OpenSky country NAMES → ISO2 without
//                       a JSON import
//   LICENSE             MIT text as shipped in the package
//   SOURCE.md           provenance
//
// Usage: node scripts/fetch-flags.mjs   (needs npm + tar on PATH)

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const FLAG_ICONS_VERSION = '7.5.0';
const OUT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/data/local_data/flags');

/**
 * Pick the ISO 3166-1 entries of flag-icons' country.json. Pure — exported
 * for tests. Sub-national codes (gb-eng, es-ct…) and organisations (eu, un…)
 * are dropped; codes are lower-case two letters.
 * @param {Array<{code:string,name:string,iso?:boolean}>} list
 * @returns {Array<{code:string,name:string}>}
 */
export function selectIsoCountries(list) {
  return (Array.isArray(list) ? list : [])
    .filter((c) => c && c.iso === true && /^[a-z]{2}$/.test(String(c.code || '')))
    .map((c) => ({ code: c.code, name: String(c.name || '').trim() }))
    .sort((a, b) => a.code.localeCompare(b.code));
}

function main() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'oko-flag-icons-'));
  console.log(`[Build:Flags] npm pack flag-icons@${FLAG_ICONS_VERSION} → ${tmp}`);
  execFileSync('npm', ['pack', `flag-icons@${FLAG_ICONS_VERSION}`, '--silent', '--pack-destination', tmp], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  const tgz = fs.readdirSync(tmp).find((f) => f.endsWith('.tgz'));
  if (!tgz) throw new Error('npm pack produced no tarball');
  // Bare file name + cwd: MSYS tar reads `C:\…` as a remote host ("Cannot
  // connect to C"), so the archive must be addressed without a drive colon.
  execFileSync('tar', ['-xzf', tgz], { stdio: 'inherit', cwd: tmp });
  const pkg = path.join(tmp, 'package');
  const meta = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'), 'utf8'));
  if (meta.version !== FLAG_ICONS_VERSION) throw new Error(`unexpected version ${meta.version}`);
  const countries = selectIsoCountries(JSON.parse(fs.readFileSync(path.join(pkg, 'country.json'), 'utf8')));

  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(path.join(OUT_DIR, '4x3'), { recursive: true });
  let bytes = 0;
  for (const c of countries) {
    const src = path.join(pkg, 'flags', '4x3', `${c.code}.svg`);
    const svg = fs.readFileSync(src);
    bytes += svg.length;
    fs.writeFileSync(path.join(OUT_DIR, '4x3', `${c.code}.svg`), svg);
  }
  fs.copyFileSync(path.join(pkg, 'LICENSE'), path.join(OUT_DIR, 'LICENSE'));
  fs.writeFileSync(path.join(OUT_DIR, 'countries.js'), `// GENERATED by scripts/fetch-flags.mjs from flag-icons@${FLAG_ICONS_VERSION} country.json (MIT). Do not edit.
export const FLAG_ICONS_VERSION = '${FLAG_ICONS_VERSION}';
/** ISO 3166-1 alpha-2 (lower-case) → English short name, as flag-icons ships it. */
export const COUNTRIES = Object.freeze(${JSON.stringify(countries)});
`, 'utf8');
  const built = new Date().toISOString().split('T')[0];
  fs.writeFileSync(path.join(OUT_DIR, 'SOURCE.md'), `# Country flags (flag-icons)

## Provenance
- **Source:** [flag-icons](https://github.com/lipis/flag-icons) by Panayiotis Lipiridis and contributors, npm package \`flag-icons@${FLAG_ICONS_VERSION}\` (integrity via the npm registry tarball).
- **License:** **MIT** (\`LICENSE\` copied here). Attribution is not required by MIT but is given in the Data attribution popover.
- **What is kept:** the ${countries.length} ISO 3166-1 flags in 4:3 (\`flags/4x3/*.svg\`) and the code→name table from \`country.json\` (as \`countries.js\`). Sub-national and organisation flags are not bundled — cards flag STATES only.

## Build
- **Built:** ${built} by \`scripts/fetch-flags.mjs\`; ${(bytes / 1024).toFixed(0)} KB of SVG, lazy-loaded one file at a time by \`src/data/countryFlags.js\`.

## Use in OKO
- Aircraft: registration country (adsbdb \`registered_owner_country_iso_name\`, fallback OpenSky \`origin_country\` name → ISO2), route airports (adsbdb \`country_iso_name\`).
- Ships: flag state from the MMSI MID prefix (\`local_data/mids\`).
`, 'utf8');
  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(`[Build:Flags] wrote ${countries.length} flags (${(bytes / 1024).toFixed(0)} KB) → ${OUT_DIR}`);
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isDirectRun) {
  try { main(); } catch (err) { console.error('[Build:Flags] Failed:', err); process.exit(1); }
}
