// Account-center additions are merged into the existing SK/EN dictionaries.
// 2026-09-26: Slovak copy uses the formal address (vykanie) throughout the account
// surface — one voice from the launcher to the security page; new keys for the
// account menu, the password-strength meter and the sign-in hero column.
export const AUTH_EN = {
  'auth.photo': 'Your avatar photo', 'auth.choose-photo': 'Choose photo', 'auth.save-photo': 'Save photo',
  'auth.remove-photo': 'Remove photo', 'auth.photo-saved': 'Avatar photo saved.', 'auth.photo-removed': 'Photo removed. Your profile symbol is active.',
  'auth.photo-hint': 'JPG, PNG or WebP · up to 5 MB and 16 megapixels. Automatically cropped to a square.',
  'auth.photo-fallback': 'Your photo is private to your account. Removing it restores the symbol selected below.',
  'auth.photo-preview-note': 'Preview only — press Save photo to upload.', 'auth.photo-uploading': 'Uploading and processing photo…',
  'auth.error.photo_format': 'Choose a JPG, PNG or WebP image. SVG and other file types are not supported.',
  'auth.error.photo_size': 'Choose a non-empty photo no larger than 5 MB.',
  'auth.error.photo_invalid': 'The photo could not be processed. Use a valid, still image up to 16 megapixels.',
  'auth.error.photo_busy': 'Photo processing is busy. Please try again shortly.',
  'auth.event.photo_updated': 'Avatar photo updated', 'auth.event.photo_removed': 'Avatar photo removed',
  'auth.center': 'Account center', 'auth.overview': 'Overview', 'auth.security': 'Security',
  'auth.created-date': 'Member since',
  'auth.devices': 'Devices', 'auth.activity': 'Activity', 'auth.edit-profile': 'Edit profile',
  'auth.signed-in': 'Signed in', 'auth.guest': 'Not signed in', 'auth.unknown': 'Status unavailable',
  'auth.member': 'Member', 'auth.greeting': 'Welcome, {name}', 'auth.account-ready': 'Your account, under your control.',
  'auth.bio': 'About you', 'auth.bio-hint': 'Up to 280 characters. Only visible in your account.',
  'auth.avatar': 'Profile symbol', 'auth.avatar-color': 'Accent color',
  'auth.avatar.orbit': 'Orbit', 'auth.avatar.radar': 'Radar', 'auth.avatar.globe': 'Globe',
  'auth.avatar.satellite': 'Satellite', 'auth.avatar.map': 'Map', 'auth.avatar.compass': 'Compass',
  'auth.color.cyan': 'Cyan', 'auth.color.green': 'Green', 'auth.color.amber': 'Amber', 'auth.color.violet': 'Violet',
  'auth.current-password': 'Current password', 'auth.new-password': 'New password',
  'auth.change-password': 'Change password', 'auth.password-note': 'Confirm your current password. All other devices will be signed out.',
  'auth.password-changed': 'Password changed. Other devices have been signed out.',
  'auth.password-updated': 'Password updated', 'auth.last-login': 'Last sign-in', 'auth.not-recorded': 'Not recorded yet',
  'auth.email-verified': 'Email verified', 'auth.email-pending': 'Email not verified',
  'auth.verify-email': 'Verify email', 'auth.verification-sent': 'Verification instructions sent. Check your inbox.',
  'auth.email-confirmed': 'Email confirmed. You can sign in with your current address.',
  'auth.mail-unavailable': 'Email delivery is not configured. Verification, email changes and password recovery are unavailable until the administrator connects a mail service.',
  'auth.local-email': 'This is a local test address, not a real mailbox. Use a real email address once delivery is configured.',
  'auth.change-email': 'Change email', 'auth.new-email': 'New email address',
  'auth.email-change-note': 'Your current address stays active until you confirm the new one. Confirmation signs out existing sessions.',
  'auth.email-change-sent': 'Check your new inbox to confirm the change. Your current address remains active.',
  'auth.forgot': 'Forgot password?', 'auth.recovery-title': 'Recover your account',
  'auth.send-reset': 'Send recovery link', 'auth.reset-requested': 'If this account can be recovered, instructions will arrive by email.',
  'auth.reset-title': 'Set a new password', 'auth.reset-password': 'Save new password',
  'auth.reset-done': 'Your password was reset and all sessions signed out. Sign in with your new password.',
  'auth.confirm-email-title': 'Confirm your email', 'auth.confirm-link': 'Confirm email address',
  'auth.link-note': 'Continue only if you requested this change. The link can be used once.',
  'auth.back-login': 'Back to sign in', 'auth.back-globe': 'Back to the globe',
  'auth.sessions-note': 'Recognize every session? Sign out any you no longer use. Device labels are approximate, not a verified device inventory.',
  'auth.this-device': 'This session', 'auth.seen': 'Last active', 'auth.expires': 'Expires',
  'auth.revoke': 'Sign out session', 'auth.revoke-others': 'Sign out other sessions',
  'auth.revoke-confirm': 'Sign out this session? It will need to sign in again.',
  'auth.revoke-others-confirm': 'Sign out all other sessions? This session will stay signed in.',
  'auth.confirm-action': 'Confirm sign-out', 'auth.cancel': 'Cancel', 'auth.revoked': 'Session access revoked.',
  'auth.no-other-devices': 'Only this session is active.', 'auth.loading-security': 'Loading account security…',
  'auth.security-error': 'Could not load devices and activity.', 'auth.refresh': 'Refresh',
  'auth.activity-note': 'Recent successful account actions. This is not a record of your activity on the globe.',
  'auth.no-events': 'No recorded events yet.', 'auth.export': 'Download my account data',
  'auth.export-note': 'JSON file with your profile, session details and account events. No passwords or access tokens.',
  'auth.exported': 'Account data downloaded.', 'auth.plan': 'Access', 'auth.free': 'Free account',
  'auth.plan-note': 'The globe and current layers are open to everyone. No subscription or payment method is attached.',
  'auth.session-expired': 'Your session has ended. Sign in again to manage your account.',
  'auth.profile-progress': 'Profile setup', 'auth.profile-name-ready': 'Display name added',
  'auth.profile-bio-ready': 'Short bio added', 'auth.profile-email-ready': 'Email confirmed',
  'auth.saved-note': 'Your changes are stored on your account, across devices.',
  'auth.error.invalid_bio': 'Use at most 280 characters without control characters.',
  'auth.error.invalid_avatar': 'Choose one of the available profile symbols and colors.',
  'auth.error.invalid_current_password': 'The current password is incorrect.',
  'auth.error.password_unchanged': 'Choose a password different from your current one.',
  'auth.error.mail_unavailable': 'Email delivery is not configured. Contact the administrator.',
  'auth.error.invalid_token': 'This link is invalid or has expired. Request a new one.',
  'auth.error.email_unavailable': 'This email cannot be used. Try another address.',
  'auth.error.session_not_found': 'This session has already ended. Refresh the list.',
  'auth.event.register': 'Account created', 'auth.event.login': 'Signed in', 'auth.event.logout': 'Signed out',
  'auth.event.password_changed': 'Password changed', 'auth.event.password_reset': 'Password reset',
  'auth.event.profile_updated': 'Profile updated', 'auth.event.session_revoked': 'Session signed out',
  'auth.event.sessions_revoked': 'Other sessions signed out', 'auth.event.email_verified': 'Email verified',
  'auth.event.email_changed': 'Email changed', 'auth.event.email_change_requested': 'Email change requested',
  'auth.event.verification_requested': 'Email verification requested', 'auth.event.owner_created': 'Owner account created',
  'auth.event.unknown': 'Account updated',
  'auth.event.registered': 'Account created', 'auth.event.other_sessions_revoked': 'Other sessions signed out',
  'auth.event.password_reset_requested': 'Password recovery requested',
  'auth.error.credentials_changed': 'Your credentials changed. Refresh and sign in again.',
  'auth.error.invalid_avatar_color': 'Choose one of the available accent colors.',
  // 2026-09-26: launcher menu, strength meter, hero column, inline hints.
  'auth.menu': 'Account menu', 'auth.open-center': 'Open account center',
  'auth.continue-guest': 'Continue without an account',
  'auth.caps-lock': 'Caps Lock is on',
  'auth.strength.label': 'Password strength',
  'auth.strength.empty': 'At least 15 characters — a passphrase of several words works best',
  'auth.strength.short': 'Too short — at least 15 characters',
  'auth.strength.fair': 'Meets the minimum', 'auth.strength.good': 'Good', 'auth.strength.strong': 'Strong', 'auth.strength.excellent': 'Excellent',
  'auth.hero-title': 'Your OKO account',
  'auth.hero-1': 'Profile, avatar and display name — the same on every device',
  'auth.hero-2': 'Overview of signed-in sessions and devices; sign any of them out',
  'auth.hero-3': 'Download your own account data at any time',
  'auth.hero-note': 'The globe and all layers stay open without an account.',
  'auth.field-error': 'Check this field',
  'auth.hero-4': 'Followed flights — saved to your account, at the top of Search',
  'follow.login-reason': 'Following flights needs an account. Sign in or create one — the selected flight is then added automatically.',
};
export const AUTH_SK = {
  'auth.photo': 'Vaša profilová fotka', 'auth.choose-photo': 'Vybrať fotku', 'auth.save-photo': 'Uložiť fotku',
  'auth.remove-photo': 'Odstrániť fotku', 'auth.photo-saved': 'Profilová fotka je uložená.', 'auth.photo-removed': 'Fotka je odstránená. Používa sa váš profilový symbol.',
  'auth.photo-hint': 'JPG, PNG alebo WebP · najviac 5 MB a 16 megapixelov. Automatický orez na štvorec.',
  'auth.photo-fallback': 'Fotka je súkromná, viditeľná len vo vašom účte. Po odstránení sa zobrazí symbol vybraný nižšie.',
  'auth.photo-preview-note': 'Zatiaľ iba náhľad — nahranie potvrďte tlačidlom Uložiť fotku.', 'auth.photo-uploading': 'Nahrávam a spracúvam fotku…',
  'auth.error.photo_format': 'Vyberte obrázok JPG, PNG alebo WebP. SVG a iné súbory nie sú podporované.',
  'auth.error.photo_size': 'Vyberte neprázdnu fotku s veľkosťou najviac 5 MB.',
  'auth.error.photo_invalid': 'Fotku sa nepodarilo spracovať. Použite platný neanimovaný obrázok do 16 megapixelov.',
  'auth.error.photo_busy': 'Spracovanie fotiek je vyťažené. Skúste to o chvíľu.',
  'auth.event.photo_updated': 'Zmena profilovej fotky', 'auth.event.photo_removed': 'Odstránenie profilovej fotky',
  'auth.center': 'Centrum účtu', 'auth.overview': 'Prehľad', 'auth.security': 'Zabezpečenie',
  'auth.created-date': 'Členom od',
  'auth.devices': 'Zariadenia', 'auth.activity': 'Aktivita', 'auth.edit-profile': 'Upraviť profil',
  'auth.signed-in': 'Prihlásený', 'auth.guest': 'Neprihlásený', 'auth.unknown': 'Stav neoverený',
  'auth.member': 'Člen', 'auth.greeting': 'Vitajte, {name}', 'auth.account-ready': 'Váš účet, pod vašou kontrolou.',
  'auth.bio': 'O vás', 'auth.bio-hint': 'Najviac 280 znakov. Viditeľné iba vo vašom účte.',
  'auth.avatar': 'Symbol profilu', 'auth.avatar-color': 'Farba profilu',
  'auth.avatar.orbit': 'Orbita', 'auth.avatar.radar': 'Radar', 'auth.avatar.globe': 'Glóbus',
  'auth.avatar.satellite': 'Satelit', 'auth.avatar.map': 'Mapa', 'auth.avatar.compass': 'Kompas',
  'auth.color.cyan': 'Tyrkysová', 'auth.color.green': 'Zelená', 'auth.color.amber': 'Jantárová', 'auth.color.violet': 'Fialová',
  'auth.current-password': 'Aktuálne heslo', 'auth.new-password': 'Nové heslo',
  'auth.change-password': 'Zmeniť heslo', 'auth.password-note': 'Potvrďte aktuálne heslo. Všetky ostatné zariadenia sa odhlásia.',
  'auth.password-changed': 'Heslo je zmenené. Ostatné zariadenia boli odhlásené.',
  'auth.password-updated': 'Posledná zmena hesla', 'auth.last-login': 'Posledné prihlásenie', 'auth.not-recorded': 'Zatiaľ nezaznamenané',
  'auth.email-verified': 'E-mail overený', 'auth.email-pending': 'E-mail neoverený',
  'auth.verify-email': 'Overiť e-mail', 'auth.verification-sent': 'Pokyny na overenie boli odoslané. Skontrolujte schránku.',
  'auth.email-confirmed': 'E-mail je potvrdený. Môžete sa prihlásiť aktuálnou adresou.',
  'auth.mail-unavailable': 'Odosielanie e-mailov nie je nastavené. Overenie, zmena e-mailu a obnova hesla budú dostupné po pripojení poštovej služby správcom.',
  'auth.local-email': 'Toto je lokálna testovacia adresa, nie skutočná schránka. Po nastavení odosielania ju nahraďte svojím e-mailom.',
  'auth.change-email': 'Zmeniť e-mail', 'auth.new-email': 'Nová e-mailová adresa',
  'auth.email-change-note': 'Pôvodná adresa platí až do potvrdenia novej. Potvrdenie odhlási existujúce relácie.',
  'auth.email-change-sent': 'Potvrďte zmenu v novej schránke. Dovtedy zostáva aktívna pôvodná adresa.',
  'auth.forgot': 'Zabudnuté heslo?', 'auth.recovery-title': 'Obnoviť prístup k účtu',
  'auth.send-reset': 'Poslať odkaz na obnovu', 'auth.reset-requested': 'Ak sa tento účet dá obnoviť, pokyny prídu e-mailom.',
  'auth.reset-title': 'Nastaviť nové heslo', 'auth.reset-password': 'Uložiť nové heslo',
  'auth.reset-done': 'Heslo bolo obnovené a všetky relácie odhlásené. Prihláste sa novým heslom.',
  'auth.confirm-email-title': 'Potvrdiť e-mail', 'auth.confirm-link': 'Potvrdiť e-mailovú adresu',
  'auth.link-note': 'Pokračujte, iba ak ste túto zmenu vyžiadali. Odkaz sa dá použiť iba raz.',
  'auth.back-login': 'Späť na prihlásenie', 'auth.back-globe': 'Späť na glóbus',
  'auth.sessions-note': 'Poznáte všetky prihlásenia? Nepoužívané môžete odhlásiť. Názvy zariadení sú orientačné, nejde o overený zoznam fyzických zariadení.',
  'auth.this-device': 'Táto relácia', 'auth.seen': 'Posledná aktivita', 'auth.expires': 'Platnosť do',
  'auth.revoke': 'Odhlásiť reláciu', 'auth.revoke-others': 'Odhlásiť ostatné relácie',
  'auth.revoke-confirm': 'Odhlásiť túto reláciu? Bude sa musieť znova prihlásiť.',
  'auth.revoke-others-confirm': 'Odhlásiť všetky ostatné relácie? Toto prihlásenie zostane aktívne.',
  'auth.confirm-action': 'Potvrdiť odhlásenie', 'auth.cancel': 'Zrušiť', 'auth.revoked': 'Prístup relácie bol zrušený.',
  'auth.no-other-devices': 'Aktívne je iba toto prihlásenie.', 'auth.loading-security': 'Načítavam zabezpečenie účtu…',
  'auth.security-error': 'Zariadenia a aktivitu sa nepodarilo načítať.', 'auth.refresh': 'Obnoviť',
  'auth.activity-note': 'Posledné úspešné úkony v účte. Nejde o históriu vášho pohybu na glóbuse.',
  'auth.no-events': 'Zatiaľ žiadne zaznamenané udalosti.', 'auth.export': 'Stiahnuť údaje môjho účtu',
  'auth.export-note': 'JSON súbor s profilom, reláciami a udalosťami účtu. Bez hesiel a prístupových tokenov.',
  'auth.exported': 'Údaje účtu boli stiahnuté.', 'auth.plan': 'Prístup', 'auth.free': 'Bezplatný účet',
  'auth.plan-note': 'Glóbus a aktuálne vrstvy sú verejné. K účtu nie je pripojené predplatné ani platobná karta.',
  'auth.session-expired': 'Vaše prihlásenie sa skončilo. Na správu účtu sa prihláste znova.',
  'auth.profile-progress': 'Dokončenie profilu', 'auth.profile-name-ready': 'Vyplnené meno',
  'auth.profile-bio-ready': 'Doplnené predstavenie', 'auth.profile-email-ready': 'Overený e-mail',
  'auth.saved-note': 'Zmeny sú uložené v účte a dostupné aj na ostatných zariadeniach.',
  'auth.error.invalid_bio': 'Použite najviac 280 znakov bez riadiacich znakov.',
  'auth.error.invalid_avatar': 'Vyberte jeden z dostupných symbolov a farieb profilu.',
  'auth.error.invalid_current_password': 'Aktuálne heslo nie je správne.',
  'auth.error.password_unchanged': 'Zvoľte iné heslo než to aktuálne.',
  'auth.error.mail_unavailable': 'Odosielanie e-mailov nie je nastavené. Kontaktujte správcu.',
  'auth.error.invalid_token': 'Odkaz je neplatný alebo vypršal. Vyžiadajte si nový.',
  'auth.error.email_unavailable': 'Tento e-mail sa nedá použiť. Skúste inú adresu.',
  'auth.error.session_not_found': 'Táto relácia už skončila. Obnovte zoznam.',
  'auth.event.register': 'Vytvorenie účtu', 'auth.event.login': 'Prihlásenie', 'auth.event.logout': 'Odhlásenie',
  'auth.event.password_changed': 'Zmena hesla', 'auth.event.password_reset': 'Obnova hesla',
  'auth.event.profile_updated': 'Úprava profilu', 'auth.event.session_revoked': 'Odhlásenie relácie',
  'auth.event.sessions_revoked': 'Odhlásenie ostatných relácií', 'auth.event.email_verified': 'Overenie e-mailu',
  'auth.event.email_changed': 'Zmena e-mailu', 'auth.event.email_change_requested': 'Žiadosť o zmenu e-mailu',
  'auth.event.verification_requested': 'Žiadosť o overenie e-mailu', 'auth.event.owner_created': 'Vytvorenie účtu vlastníka',
  'auth.event.unknown': 'Aktualizácia účtu',
  'auth.event.registered': 'Vytvorenie účtu', 'auth.event.other_sessions_revoked': 'Odhlásenie ostatných relácií',
  'auth.event.password_reset_requested': 'Žiadosť o obnovu hesla',
  'auth.error.credentials_changed': 'Prihlasovacie údaje sa zmenili. Obnovte stránku a prihláste sa znova.',
  'auth.error.invalid_avatar_color': 'Vyberte jednu z dostupných farieb profilu.',
  // 2026-09-26: ponuka účtu, merač sily hesla, stĺpec „prečo účet", inline hlášky.
  'auth.menu': 'Ponuka účtu', 'auth.open-center': 'Otvoriť centrum účtu',
  'auth.continue-guest': 'Pokračovať bez účtu',
  'auth.caps-lock': 'Caps Lock je zapnutý',
  'auth.strength.label': 'Sila hesla',
  'auth.strength.empty': 'Aspoň 15 znakov — najlepšie funguje fráza z niekoľkých slov',
  'auth.strength.short': 'Príliš krátke — aspoň 15 znakov',
  'auth.strength.fair': 'Spĺňa minimum', 'auth.strength.good': 'Dobré', 'auth.strength.strong': 'Silné', 'auth.strength.excellent': 'Výborné',
  'auth.hero-title': 'Váš účet v OKO',
  'auth.hero-1': 'Profil, avatar a zobrazované meno — rovnaké na každom zariadení',
  'auth.hero-2': 'Prehľad prihlásení a zariadení; ktorékoľvek z nich môžete odhlásiť',
  'auth.hero-3': 'Údaje svojho účtu si kedykoľvek stiahnete',
  'auth.hero-note': 'Glóbus a všetky vrstvy zostávajú prístupné aj bez účtu.',
  'auth.field-error': 'Skontrolujte toto pole',
  'auth.hero-4': 'Sledované lety — uložené k účtu, navrchu v hľadaní',
  'follow.login-reason': 'Sledovanie letov je pre prihlásených. Prihláste sa alebo si vytvorte účet — vybraný let sa potom pridá sám.',
};
